version: "3.9"

services:
  database:
    image: postgres
    container_name: database_app
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=curso
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app_aluguel
    volumes:
      - pgdata:/data/postgres
  app_aluguel:
    build: .
    container_name: app_aluguel
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
